site_name: Latent Self
theme:
  name: material
nav:
  - Home: index.md
  - Architecture: architecture.puml
  - Deployment: deployment.md
  - User Manual: user_manual.md
  - Troubleshooting: troubleshooting.md
  - Release Process: release.md
  - Documentation Strategy: documentation_strategy.md
  - Docs as Code: docs_as_code.md
  - Legacy Doc Inventory: legacy_doc_inventory.md
  - Setup Guide: setup_guide.md

docs_dir: docs
