site_name: Latent Self
theme:
  name: material
nav:
  - Home: index.md
  - Architecture: architecture.puml
  - Deployment: deployment.md
  - User Manual: user_manual.md
  - Troubleshooting: troubleshooting.md

docs_dir: docs
