site_name: Latent Self Demo Portal
theme:
  name: material
plugins:
  - search
nav:
  - Home: index.md
  - Evaluation: ../docs/portal_evaluation.md

# Use the main docs directory for now
docs_dir: ../docs
