name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt -r requirements-test.txt mypy ruff black pre-commit mkdocs mkdocs-material pyinstaller
      - run: pre-commit run --all-files --show-diff-on-failure
      - run: pytest -q
      - run: mkdocs build --strict
      - run: python scripts/build_bundle.py
      - uses: actions/upload-artifact@v4
        with:
          name: latent-self-${{ matrix.os }}
          path: dist/
